const lipsum =  <p> 
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer rutrum rutrum tristique. Donec fermentum nunc feugiat, lacinia sem ac, semper diam. Phasellus euismod lacus arcu, ac viverra nisi vulputate vitae. Sed nunc ex, dapibus fermentum dapibus fermentum, aliquam a nunc. Praesent in placerat massa. Vestibulum at consequat orci, at fermentum libero. Nam ultrices tristique lacus, nec feugiat odio blandit eu. Nam enim lacus, pretium in ligula at, commodo elementum justo.
                    <br className="mb-3"/>
                    Vivamus vel gravida magna, nec consequat diam. Integer volutpat sapien fringilla accumsan pretium. Duis fermentum ligula vel dolor bibendum, quis vestibulum enim vehicula. Mauris quis quam vitae lorem congue aliquam. Vivamus quis urna luctus, sagittis risus eget, ultrices turpis. Phasellus ullamcorper ultricies velit, ac volutpat ex sollicitudin vel. Praesent nec maximus libero, dignissim consequat nisl. Cras dignissim libero vitae ipsum efficitur bibendum. Vivamus pulvinar diam et sapien mollis, eget varius orci consectetur. In eu dignissim tortor.
                    <br className="mb-3"/>
                    Sed condimentum egestas semper. Mauris sed tortor libero. Fusce non euismod ipsum. Ut purus lectus, blandit at odio at, porta pretium purus. Ut aliquam ipsum magna, non bibendum velit blandit ornare. Vivamus at mauris at leo varius commodo. Praesent in arcu a risus malesuada euismod quis egestas mi. Vestibulum nulla nisl, vehicula ac tristique vitae, porta nec ipsum.
                    <br className="mb-3"/>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rutrum leo tortor. Curabitur vitae ante ipsum. Suspendisse in suscipit ante. Maecenas in commodo nibh. Phasellus eros leo, ultrices ac venenatis vitae, pretium ac libero. Duis in augue ac urna mollis luctus. Vivamus pellentesque velit ligula, eget volutpat felis interdum id. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris ac ex et tellus luctus mattis. Praesent vehicula leo non leo auctor sollicitudin sed in quam.
                    <br className="mb-3"/>
                    Curabitur nec enim rhoncus, condimentum elit elementum, hendrerit lorem. Maecenas ac auctor orci, ut porta leo. Nulla pulvinar ligula ut odio molestie venenatis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum sodales velit neque. Nunc placerat tortor eu augue molestie scelerisque. Sed laoreet maximus tortor, sed hendrerit ante sodales non. Vivamus gravida risus et auctor finibus. Quisque eget lacus vel quam sollicitudin ullamcorper in id ante. Proin porttitor metus sapien, non porttitor risus tempor eget. Morbi sagittis diam ac nisi mattis, in lacinia dui interdum.
                    <br className="mb-3"/>
                    Nulla sit amet libero magna. In hac habitasse platea dictumst. Donec neque sapien, suscipit eget vestibulum nec, lacinia ut nisl. In ac orci imperdiet, varius sem at, condimentum lorem. Suspendisse at ligula rhoncus nibh porta aliquet sed ac felis. Vestibulum vel cursus lorem, vitae commodo elit. Fusce ullamcorper vel libero sed ultricies. Morbi malesuada, nibh a vestibulum lobortis, sapien ante cursus lorem, quis sagittis nunc augue vitae leo. Curabitur volutpat orci non magna elementum viverra. Vestibulum vel blandit urna. Praesent pretium orci nec metus aliquam, at pretium eros maximus.
                    <br className="mb-3"/>
                    Ut quis purus dui. Duis ultrices dictum augue id lacinia. Vestibulum et placerat eros. Phasellus est libero, dapibus sit amet sem sed, lobortis bibendum enim. Morbi quis mi id ante euismod suscipit. Sed eu congue tortor. Duis urna odio, condimentum eleifend congue non, vulputate non elit. Nulla consectetur quam sit amet magna varius dictum ut vel urna. Vestibulum ac sollicitudin diam, lobortis ornare justo. Morbi suscipit nibh in tincidunt bibendum. Vivamus semper lacinia eleifend. Quisque luctus elit leo, sed porta sem blandit eget. Pellentesque convallis mattis mauris, ut feugiat sapien tincidunt ac. Aenean eu pharetra mi, id lacinia turpis. Sed quis justo justo.
                    <br className="mb-3"/>
                    In pharetra est at urna rhoncus dapibus. Proin mattis dui vel dolor interdum venenatis. Ut interdum ut augue in dapibus. Vestibulum at orci vel mauris mattis maximus sit amet at justo. Nunc mattis ac est egestas venenatis. Suspendisse posuere ex ut suscipit porta. Mauris vel tortor erat. Sed tristique sem nulla. Nunc eu scelerisque justo. Phasellus vehicula lacinia lobortis.
                    <br className="mb-3"/>
                    Nulla mollis turpis sed ligula consectetur placerat. Morbi ornare a leo at maximus. Integer eget blandit urna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur ut ultrices diam. Vestibulum a molestie lectus, vitae sodales lectus. Sed tristique ullamcorper imperdiet. Nulla ultricies, ex vel finibus posuere, ipsum risus tincidunt libero, quis congue purus ante dignissim massa. Nunc ut ullamcorper turpis.
                    <br className="mb-3"/>
                    Phasellus vulputate suscipit urna. Curabitur venenatis, tellus vel malesuada condimentum, ante sem ultrices metus, quis tincidunt lorem erat vel ipsum. Fusce molestie odio quis varius gravida. Fusce tortor dui, viverra ac blandit sit amet, pretium eget arcu. Phasellus egestas mauris in nisl condimentum efficitur. Mauris eget magna a urna consequat maximus. In eget suscipit nunc. Maecenas vitae tortor sodales, facilisis magna a, varius lorem. Pellentesque gravida eu leo et aliquam. Sed a mi id lectus cursus condimentum in sit amet nisi.
                    <br className="mb-3"/>
                    Quisque at est et velit rutrum congue ut non sem. Sed in consequat ipsum. Duis sit amet commodo neque. Nullam non augue sit amet mi vulputate auctor. Integer non magna ornare, tempus est a, vestibulum elit. Ut volutpat, dolor at semper suscipit, est quam porta risus, sed gravida turpis eros ut augue. Etiam eu turpis faucibus, fermentum ex vitae, tempor mi.
                    <br className="mb-3"/>
                    Aenean libero leo, fringilla ut ante vel, ornare tristique urna. Morbi imperdiet hendrerit dui, nec blandit augue blandit vel. Quisque non ornare libero, eget dapibus augue. Suspendisse accumsan non dui ac pellentesque. Vestibulum at turpis eu enim efficitur dapibus. Mauris nibh sem, scelerisque et fringilla et, iaculis et elit. Praesent hendrerit elit sed tincidunt tincidunt. Maecenas venenatis massa id lacinia laoreet. Praesent ac erat sapien. Maecenas semper lacus non sem finibus, in volutpat neque rutrum. Vestibulum pellentesque pharetra lacus sit amet maximus. Nam tristique enim pharetra cursus sodales. Nam neque arcu, condimentum quis auctor eget, condimentum non metus. Quisque faucibus nisi sed velit mattis, ac eleifend libero dapibus. Aenean vel vestibulum nisl.
                    <br className="mb-3"/>
                    Donec quis nunc in felis sollicitudin rhoncus quis sollicitudin risus. Ut vitae molestie ipsum. Ut facilisis, sem eget aliquam placerat, arcu elit posuere leo, id tempor ante enim ultricies nibh. Nullam maximus elit quis scelerisque tempor. Curabitur risus mi, euismod a tempus eget, lacinia id odio. Etiam dignissim justo et est ultricies consectetur. Nullam vestibulum aliquet velit vel dictum. Aliquam erat volutpat.
                </p>

export default lipsum